name: lazytext

on:
  pull_request:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/ci.txt
        pip install -e .

    - name: Test
      run: python -m pytest tests/

    - name: Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install codecov
        codecov

  CD:
    needs: CI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: PyPi Deploy preparation
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel --universal
    - name: PyPi Deploy
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: ${{ secrets.PYPI_USER }}
        password: ${{ secrets.PYPI_PASSWORD }}
